Fixing version number
SasView/sasview pull request #1874
Opened 2021-06-21 08:24 UTC by wpotrzebowski

The previous proposal with 5.x.x-alpha1 didn't work with StrictVersion from distutils. The alternative is to use a1 label e.g. 5.0.5a1

2021-06-21 08:24 UTC, wpotrzebowski commented
ready for testing on OSX

2021-06-21 14:19 UTC, butlerpd commented
Does this mean that the `dev` nomenclature suggested in #1872 from PEP 440 not resolve properly?

2021-06-21 20:38 UTC, wpotrzebowski commented
ready for testing on Windows

2021-06-21 20:38 UTC, wpotrzebowski commented
ready for testing on Win

2021-06-21 21:32 UTC, krzywon requested changes
This fixes the loading issue, but the docstrings need to match the functionality or someone might repeat this mistake in the future.

2021-06-21 21:32 UTC, krzywon commented on docs/sphinx-docs/source/conf.py
> +release = '5.0.5a1'
The existing docstring is no longer valid and should be changed. Adding a link to the StrictVersion rules should suffice.

http://epydoc.sourceforge.net/stdlib/distutils.version.StrictVersion-class.html

2021-06-21 21:32 UTC, krzywon commented on src/sas/sasview/__init__.py
>  StrictVersion(__version__)
Same as my other comment.

2021-06-23 04:40 UTC, wpotrzebowski commented
ready for testing on OSX

2021-06-23 04:40 UTC, wpotrzebowski commented
ready for testing on Linux

2021-06-23 11:34 UTC, krzywon approved these changes

2021-06-23 11:35 UTC, krzywon commented
I havent looked at why the builds are failing in this case, but everything here looks good now.

2021-06-24 11:58 UTC, wpotrzebowski commented
> I havent looked at why the builds are failing in this case, but everything here looks good now.

Yes, builds are still failing. I am trying to look into this.

2021-06-29 20:54 UTC, merged