[v5.0.6] Update installer.iss with correct version and copyright dates
SasView/sasview pull request #2434
Opened 2023-02-06 15:45 UTC by krzywon

## Description
This updates the version and copyright date in installer.iss for v5.0.6.

## Review Checklist (please remove items if they don't apply):

- [ ] Code has been reviewed
- [ ] Functionality has been tested
- [ ] Windows installer (GH artifact) has been tested (installed and worked) 
- [ ] MacOSX installer (GH artifact) has been tested (installed and worked) 
- [ ] User documentation is available and complete (if required)
- [ ] Developers documentation is available and complete (if required)
- [ ] The introduced changes comply with SasView license (BSD 3-Clause)

2023-02-06 15:57 UTC, butlerpd commented
I think it is too late for b1. The question however might be whether to change this to 5.0.6 (for all betas even) on the grounds that the final 5.0.6 will just be in the same directory?  When launching the version number is now prominently displayed in the top left corner of the SasView application window.  This would make releases a bit easier ... and less worry that the final release will default to 5.0.6bx instead of 5.0.6?

2023-02-12 23:11 UTC, butlerpd requested changes

2023-02-12 23:11 UTC, butlerpd commented on installers/installer.iss
> +#define MyAppVersion "5.0.6b1"
For the installer we should just use 5.0.6 (for the betas and the final release).  Betas should be overwritten by the final release in any case.  Once that is changed this should be ready to merge.

2023-02-12 23:12 UTC, butlerpd commented
also .. why is it failing ubuntu unit tests?

2023-02-14 14:07 UTC, krzywon commented
> also .. why is it failing ubuntu unit tests?

The ubuntu failures were due to intermittent connection issues with azure.

2023-02-14 14:28 UTC, merged