2990 - Fixed units in scaled plots
SasView/sasview pull request #2992
Opened 2024-07-26 12:38 UTC by lucas-wilkins

There were some issues with variable re-use that caused the wrong units to appear on some of the differently scaled plots. Fixes this.

2024-07-26 21:00 UTC, rozyczko requested changes
Actual fix is working well. However, there are additional things modified/changed which should be made a separate PR, since they don't have anything to do with the current issue.

2024-07-27 10:03 UTC, lucas-wilkins commented on src/sas/qtgui/Utilities/GuiUtils.py
> +                                                           options)
I'm pretty confused by where this came from, it wasn't me

2024-07-27 10:03 UTC, lucas-wilkins commented on src/sas/qtgui/Utilities/GuiUtils.py
> +            return QtGui.QValidator.Acceptable
again, I didn't do this

2024-07-27 10:03 UTC, lucas-wilkins commented on src/sas/qtgui/Utilities/GuiUtils.py
> -
dunno

2024-07-27 10:05 UTC, lucas-wilkins commented
Clearly something has gone very wrong with this commit. Need to make a new one.

2024-07-29 06:43 UTC, lucas-wilkins commented on src/sas/qtgui/Utilities/GuiUtils.py
> +            return QtGui.QValidator.Acceptable
restored to previous code

2024-07-29 06:43 UTC, lucas-wilkins commented on src/sas/qtgui/Utilities/GuiUtils.py
> +            return QtGui.QValidator.Intermediate
restored to previous code

2024-07-29 06:43 UTC, lucas-wilkins commented on src/sas/qtgui/Utilities/GuiUtils.py
> -
restored to previous code

2024-07-29 06:44 UTC, lucas-wilkins commented
@rozyczko Could you check that this is now correct?

2024-07-29 07:00 UTC, rozyczko approved these changes
looks good now!

2024-07-29 09:14 UTC, merged