3109: Bumps FitProblem fix
SasView/sasview pull request #3110
Opened 2024-09-10 21:05 UTC by krzywon

## Description

This uses the new interface for bumps where every fit problem is multi-fit. Iterating through the models now directly returns the fitness object instead of the individual fit problem. This change brings SasView in line with this new behavior.

Note - this only fixes one of the issues related to this major change. Fits still fail, but this fix gets it closer. See the issue for more info.

Refs #3109

## Review Checklist:

**Licencing** (untick if necessary)
- [x] The introduced changes comply with SasView license (BSD 3-Clause)

2024-09-13 07:02 UTC, rozyczko requested changes
The code looks good but I still get this message when trying to fit.

```
File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2115, in fitComplete
AttributeError: 'str' object has no attribute 'fitness'
```

2024-09-13 07:02 UTC, rozyczko commented on .github/workflows/ci.yml
> +          mv sasdata/example_data/* ../sasview/src/sas/example_data/
Using this build:

https://github.com/SasView/sasview/actions/runs/10814069439

2024-09-13 12:44 UTC, krzywon commented
@rozyczko - The fitting error is expected. This work, as noted in the pull request, only gets SasView to build and launch with the latest version of bumps. There is an outstanding issue how fitting packages parameters and what bumps expects.

2024-09-13 12:54 UTC, rozyczko commented
Alternatively, we can use the last release of bumps?
`git clone --depth=1 --branch v0.9.3 https://github.com/bumps/bumps.git ../bumps`

2024-09-19 06:55 UTC, rozyczko approved these changes
this does look good as the first step in solving the interoperability issue.

2024-09-20 04:08 UTC, wpotrzebowski commented
I am getting the same error #3109, while testing #3100. Should we also make the same fix 6.0.0?

2024-10-25 14:52 UTC, merged