Update model editor (rebase)
SasView/sasview pull request #3135
Opened 2024-10-25 15:50 UTC by krzywon

## Description

This is a rebase of the branch in #2918, from `release_6.0.0` to `main`, using interactive mode to eliminate the extra merge commit from a separate branch. This should be a parallel PR at this point, but will require some checking. The changes and checklists can all be seen in the original PR.

2024-10-26 19:34 UTC, wpotrzebowski commented
Started testing functionality on Mac and getting error when clicking on Apply 

`21:33:47 - ERROR: Traceback (most recent call last): File "sas/qtgui/Utilities/TabbedModelEditor.py", line 269, in onApply File "sas/qtgui/Utilities/TabbedModelEditor.py", line 366, in updateFromPlugin File "sas/qtgui/Utilities/TabbedModelEditor.py", line 668, in canWriteModel AttributeError: 'TabbedModelEditor' object has no attribute 'builtinmodels'`

2025-04-11 15:00 UTC, jamescrake-merani requested changes
The code is very clean. Just a few minor comments.

2025-04-11 15:00 UTC, jamescrake-merani commented on src/sas/qtgui/Utilities/PluginDefinition.py
> +        #self.addTooltip()
If this line has been commented out, can it just be removed?

2025-04-11 15:00 UTC, jamescrake-merani commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +                    else MAIN_DOC_SRC / "user" / "models" / "src" / (self.load_file + ".py")
Is this compatible with the changes made in the platformdirs branch? I can't remember if we're still using the `MAIN_DOC_SRC` constant.

2025-04-11 15:00 UTC, jamescrake-merani commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +            return
Could this be simplified by being:
```python
if not (self.is_modified and self.saveClose():
    self.reject()
```

2025-04-11 15:00 UTC, jamescrake-merani commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +            from sas.qtgui.Utilities.CodeEditor import QCodeEditor
Is there a reason this import is deferred? I know we sometimes do it when an import can take a while but is that true in this situation?

2025-04-11 15:00 UTC, jamescrake-merani commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +                # last_lines = traceback.format_exc().split('\n')[-4:]
Again, this line appears to be commented out. Can it be removed?

2025-04-11 15:00 UTC, jamescrake-merani commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +        msgBox.setText("No model checks will be run on your C file until a python file of the same name is created in your plugin directory.")
I know I'm being *very* pedantic here so feel free to ignore but Python should have a capital P.

2025-04-11 15:00 UTC, jamescrake-merani commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +        msgBox.exec_()
Why is the `exec` method being called with an underscore?

2025-04-11 15:00 UTC, jamescrake-merani commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +            #display_name = Path(self.filename_py).name
Lines commented out here.

2025-04-11 18:04 UTC, krzywon commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +        msgBox.exec_()
Both are valid in PySide6 and act the same, but `exec_()` is an older syntax that may go away. [Relevant Stackoverflow discussion](https://stackoverflow.com/questions/22610720/should-i-use-app-exec-or-app-exec-in-my-pyqt-application). I will convert to `exec()` to future-proof this.

2025-04-14 07:43 UTC, rozyczko requested changes
Some actual failures encountered, so please have a closer look

2025-04-14 07:43 UTC, rozyczko commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +            cursor = QtGui.QTextCursor(w.txtEditor.document().findBlockByLineNumber(error_line-1))
Here, `error_line` is not defined. I'm getting errors related to this when testing.

2025-04-14 07:43 UTC, rozyczko commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +            # Save files anyways
a side effect of this check is that if I hit `Escape`, the whole dialog disappears without saving or without giving users a chance to do anything.

2025-04-14 07:43 UTC, rozyczko commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +                    self.writeFile(c_file, self.c_editor_widget.getModel()['text'])
or just
```python
if py_tab_open:
    self.writeFile(py_file, self.editor_widget.getModel()['text'])
if c_tab_open:
    self.writeFile(c_file, self.c_editor_widget.getModel()['text'])

```

2025-04-14 07:43 UTC, rozyczko commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +        Remove a tab from the tab widget.
The two cases where `removeTab` is called (lines 185 and 92) use integers as arguments (`1` and `0`).
How is this going to work with this signature?

2025-04-14 07:43 UTC, rozyczko commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +            }
why not just `self.plugin_widget.chkSingle.isChecked()`?

2025-04-14 07:43 UTC, rozyczko commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
>  if __name__ == '__main__':
Not sure this is really needed. We no longer test those widgets as separate windows, but rather inside SasView. Please consider removing the whole conditional

2025-04-14 07:43 UTC, rozyczko commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +    app.exec()
The file fails the ruff check with 8 errors. Consider fixing those.

2025-04-21 19:38 UTC, krzywon commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +        Remove a tab from the tab widget.
Those instances are removing tabs from tabWidget, not calling this method. This isnt called anywhere, so I will likely remove it.

2025-04-21 19:51 UTC, krzywon commented on src/sas/qtgui/Utilities/PluginDefinition.py
> +
This is cleaner and I'll use it. My only issue with your suggestion is you must iterate through the entire column before checking if any cells in that row are empty.

2025-04-22 14:50 UTC, jamescrake-merani approved these changes
Happy with stuff on my side. I see there's one more outstanding issue that Piotr has highlighted before we merge but otherwise I think this is ready.

2025-04-28 16:01 UTC, krzywon commented
Items still outstanding for this PR that can be finished post feature-freeze:

- User documentation required for new features
- Capture keyboard interrupts gracefully in TabbedModelEditor (was this available previously?)
- Better documentation in the C model generated by the easy model editor

2025-04-28 16:07 UTC, krzywon commented on src/sas/qtgui/Utilities/TabbedModelEditor.py
> +            # Save files anyways
I agree, but for the sake of the feature freeze, I've added this as something that needs fixing during the bug fix phase of the release.

2025-04-28 22:11 UTC, butlerpd commented
I've done a functionality review though not as thorough as I would like given the time. There is one serious bug (easy to fix?) and a number of lesser issues:
* The big issue is an error in the code that adds an extra `parameters = [ ` line in front of the comment line explaining the meaning of each column (and is never closed) when generating the python file. This happens every time apply is pressed making it impossible to actually get a working model ready .
* ER should be commented out by default. With it on everything can be multiplied by S(Q). This will cause lots of confusion. However a comment above the commented out ER function explaining that uncommenting will allow it to be used with S(Q) but beware that the return value needs to be a useful value.
* It would be much better if validation was used in the parameter box. I note that if I use a string for the initial value the code defaults to making the initial guess = 1 but …
* Also there should be the new version of ER that is required for use with C models which should also be all commented out by default with explanation.
* Return should act as tab in parameter table. Once you get into the idea of hitting tab it works beautifully but return is also a common behavior and the fact that causes an extra line to be generated makes one think the "cursor" has moved to a new box somewhere but typing will erase my carefully chosen variable name - bad form...
* Default for the volume editor box should not be vol = 0 (1st polydisperse parameter * 0.0) probably times 1.0 would be good since I(Q) will be divided by that value at some point... and the default anyway is volume = 1.  A note in the comment however should mention that I(Q) will be divided by this value so the IQ equation needs to be written understanding that. It will be different than the equation they write if volume =1.
* if a C file is generated an extra line should be added to the python file with the source= line. That line should however be commented out till they have a working C file.  This last could be viewed as an extra feature as much as failure of expectation when generating  a C file?


That said, I think this is will be more helpful and less prone to users making incorrect polydisperse models as pointed out by @RichardHeenan a while back.

2025-04-29 16:32 UTC, butlerpd approved these changes
Given we have agreed to merge with bugs which will then be addressed in the bug fixing phase of the release, I am approving. Note that the change requested by Piotr seems to have been addressed? so this should be ready to merge

2025-04-30 00:48 UTC, merged